# Generated by Django 3.2.12 on 2022-04-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('UserName', models.CharField(max_length=20)),
                ('UserType', models.IntegerField()),
                ('UserPhone', models.CharField(max_length=20)),
                ('UserEmail', models.CharField(max_length=20)),
                ('UserRegTime', models.DateTimeField(auto_now_add=True)),
                ('UserLastLoginTime', models.DateTimeField(auto_now=True)),
                ('UserLoginNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=20)),
                ('ProjectDesc', models.CharField(max_length=200)),
                ('ProjectStatus', models.IntegerField()),
                ('ProjectCreateTime', models.DateTimeField(auto_now_add=True)),
                ('ProjectLastModifyTime', models.DateTimeField(auto_now=True)),
                ('ProjectCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MicroApp.userinfo')),
            ],
        ),
    ]
